# Render.com service configuration
services:
  - type: web
    name: flask-postgres-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_ENV
        value: production
      # Database configuration must be set in Render.com dashboard
      - key: DB_HOST
        value: dpg-d40c5cpr0fns73bknii0-a
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: flaskdb_3ib6_user
      - key: DB_NAME
        value: flaskdb_3ib6
      # Note: DB_PASSWORD should be set as a secret in Render.com dashboard